# Generated by Django 5.0.6 on 2024-05-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainInformation',
        ),
    ]
